# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d431e6cecd85bcb6fbe3dca9b5433e2f8262e7a2ac986b280bbb3f7beb7bc0aabe6240d235203cf7914ec3516214059c1bb5c4434a7592191b9844282a00eca5

test:
  secret_key_base: a6857f3dfc8e321117c8bfcc9642ad3336ea9f8e02c22ce12b1973766669dddbb72546f7fb596c238b08eb0da3354f576518070d43d5f63c0baff83c659c0c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
